### ISSUE TITLE
2021.6.15s when?

### ISSUE THREAD

**Issue by amsryq** [MoltenMods/UwU#1]
yes

**Comment by DaemonBeast** [comment]
@amsyarasyiq Bruh 😂

I was waiting for an official release of Reactor, but I guess since people actually want this mod updated (seriously wHaT!?), I'll make a release with an unofficial build of Reactor.

**Edit:** oh, and I forgot, some things broke so... I'm going to try and fix them, which might take a little while.

**Comment by DaemonBeast** [comment]
*There is now a pre-release* 🌈 (https://github.com/MoltenMods/UwU/releases/tag/2.0.0-pre.1)

**Comment by amsryq** [comment]
hm should i close this?

**Comment by DaemonBeast** [comment]
@amsyarasyiq Eh, it's still not a stable release yet, so I think it should remain open for now.
